FROM openjdk:16
ARG TOKEN_ARG
ARG DEV_ID_ARG
ARG BOT_ID_ARG
ARG DB_URI_ARG
ARG DB_NAME_ARG
ARG API_KEY_ARG

ENV TOKEN=$TOKEN_ARG
ENV DEV_ID=$DEV_ID_ARG
ENV BOT_ID=$BOT_ID_ARG
ENV DB_URI=$DB_URI_ARG
ENV DB_NAME=$DB_NAME_ARG
ENV API_KEY=$API_KEY_ARG

ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]